---
- hosts: all
  pre_tasks:
  - name: include environment group vars
    include_vars:
      dir: 'environments/{{ env }}/group_vars/'
      files_matching: '.*.yaml'
  - name: include environment hosts vars
    include_vars:
      dir: 'environments/{{ env }}/hosts_vars/'
      files_matching: '{{ inventory_hostname }}.yaml'
  - name: include environment secret vars
    include_vars:
      dir: 'environments/{{ env }}/hosts_vars_secret/'
      files_matching: '{{ inventory_hostname }}.secret.yaml'
  roles:
    - kubectl
