---
- name: Add Prometheus chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Add Grafana chart repo
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: "https://grafana.github.io/helm-charts"

- name: Deploy Prometheus chart with Helm
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    release_namespace: monitoring
    create_namespace: true

- name: Deploy Grafana chart with Helm
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana/grafana
    chart_version: 6.29.1
    release_namespace: monitoring
    values: "{{ lookup('template', '{{ role_path }}/files/grafana_values.yaml') | from_yaml }}"
